"""empty message

Revision ID: 7e0a8d92b14f
Revises: d1385d5559d6
Create Date: 2023-08-21 17:11:25.001993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0a8d92b14f'
down_revision = 'd1385d5559d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('is_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('is_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)

    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
